name: Build and publish a ReportVision's API
description: Build and push Docker image to the registry
inputs:
  docker-registry:
    description: The Docker registry. i.e. ghcr, acr, ecr, jfrog, docker.io
    required: true
  docker-pw:
    description: Github Token
    required: true
  docker-username:
    description: Docker registry username
    required: true
  docker-tag:
    description: Docker tag, typically an API version
    required: true
  dockerfile-path:
    description: Dockerfile path
    required: true
  docker-context-path:
    description: Path of the docker context
    required: true
  api-name:
    description: The name of the api being built
    required: true

runs:
  using: composite
  steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ inputs.docker-username }}
          password: ${{ inputs.docker-pw }}
      - name: Lowercase the repo name
        shell: bash
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.docker-context-path }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          platforms: linux/amd64
          tags: ${{ inputs.docker-registry }}/${{ env.REPO }}-${{ inputs.api-name }}:${{ inputs.docker-tag }}