ARG VERSION=v1.2.11
# The record linkage image is not specifically built for the arm64 architecture,
# so we need to explicitly state the amd64 architecture here so users running
# Docker on Apple Silicon know to build the image for the correct architecture.
FROM --platform=linux/amd64 ghcr.io/cdcgov/phdi/record-linkage:${VERSION}

RUN apt-get update && apt-get install -y curl

# Install OpenTelemetry packages for monitoring the record linkage API
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp

# Auto instrument the record linkage API
RUN opentelemetry-bootstrap -a install

# Copy our custom testing code into the container
COPY src/main.py /code/main.py
COPY src/link.py /usr/local/lib/python3.10/site-packages/phdi/linkage/link.py
COPY src/mpi.py /usr/local/lib/python3.10/site-packages/phdi/linkage/mpi.py
COPY src/dal.py /usr/local/lib/python3.10/site-packages/phdi/linkage/dal.py
