name: Deploy ReportVisions Frontend Service
description: Deploy the frontend from a tarball to Azure Blob storage in the appropriate environment.
inputs:
  deploy-env:
    description: The environment being deployed (e.g. "prod" or "test")
    required: true
  frontend-tarball:
    description: The path to the tar file containing the client code to deploy
    required: true

runs:
  using: composite
  steps:
    - name: Download Artifacts To Job
      uses: actions/download-artifact@v4
      with:
        name: frontend-tarball
    - name: Unpack frontend
      shell: bash
      run: |
        mkdir frontend-deploy;
        tar -C frontend-deploy -zxvf ${{ inputs.frontend-tarball }}
    - name: Upload frontend to the environments Azure Blob Storage
      shell: bash
      run: |
        az storage blob upload-batch -s frontend-deploy/ -d '$web' \
        --account-name reportvisionfrontend${{ inputs.deploy-env }} \
        --overwrite
    - name: Logout out of Azure
      shell: bash
      run: |
        az logout