spring:
  datasource:
    url: ${postgres_fqdn}
    username: ${postgres_user}
    password:  ${postgres_password}
    name: ${postgres_db_name}
  devtools:
    restart:
      enabled: true
      exclude: web-inf/**
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  fastapi:
    url: ${FASTAPI_URL:http://localhost:8000}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
