spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:reportvision}?sslmode=${SSL_MODE:disable}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:super_secret_password}
  devtools:
    restart:
      enabled: true
      exclude: web-inf/**
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  fastapi:
    url: ${FASTAPI_URL:http://localhost:8000}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
