name: Create, publish, deploy a OCR API image

on:
  push:
    branches: test-deploy-middleware
  # workflow_dispatch:
  #   inputs:
  #     deploy-env:
  #       description: 'The environment to deploy to'
  #       required: true
  #       type: choice
  #       options:
  #         - dev
  #         - demo
  #     ocr-docker-tag:
  #       description: 'This is optional if you would like to deploy an already published OCR-API image'
  #       required: false

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-publish-ocr:
    name: Build and Publish OCR
    runs-on: ubuntu-latest
    outputs:
      docker_inspect: ${{ steps.image_check.outputs.docker_inspect }}
      docker_tag: ${{ steps.set_tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Set OCR Docker tag
        shell: bash
        id: set_tag
        run: |
          USER_INPUT="eb399bfe9a098349d033489df425ff9b9c843e0d"
          echo "docker_tag=$(
            #this gives a new sha as default if dispatch input is empty
            echo ${USER_INPUT:-"${{ github.sha }}"}
          )" >> $GITHUB_OUTPUT
      - name: Check if image exists
        id: image_check
        run: |
          echo "docker_inspect=$(
              docker manifest inspect ghcr.io/${{ env.REPO }}-middleware:eb399bfe9a098349d033489df425ff9b9c843e0d > /dev/null ; echo $?
            )" >> $GITHUB_OUTPUT
      - name: Build and Push backend
        if: ${{ steps.image_check.outputs.docker_inspect == 1 }}
        uses: ./.github/actions/build-publish-api
        with:
          docker-registry: ghcr.io
          docker-pw: ${{ secrets.GITHUB_TOKEN }}
          docker-username: ${{ github.actor }}
          docker-tag: ${{ steps.set_tag.outputs.docker_tag }}
          dockerfile-path: ./backend/Dockerfile
          docker-context-path: ./backend/
          api-name: middleware

  deploy-ocr:
    name: Deploy OCR
    runs-on: ubuntu-latest
    environment: demo
    needs: [build-publish-ocr]
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          object-id: ${{ secrets.AZURE_OBJECT_ID }}
      - name: Deploy OCR-API
        uses: ./.github/actions/deploy-api
        with:
          deploy-env: demo
          docker-tag: eb399bfe9a098349d033489df425ff9b9c843e0d
          docker-registry: ghcr.io
          api-name: middleware
