name: Create, publish, deploy a OCR API image

on:
  push:
    branches: fix-docker-image-check
  # workflow_dispatch:
  #   inputs:
  #       tag:
  #           description: 'Version tag for new release'
  #           required: true

env:
  REGISTRY: ghcr.io
  VERSION: demo-test-env-derek1


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      tf_env: ${{ steps.set-environment.outputs.tf_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Check if image exists
        id: image_check
        run: |
          echo "tf_env=$(
              docker manifest inspect ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ env.VERSION }} > /dev/null ; echo $?
            )" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        if: ${{ steps.image_check.outputs.tf_env == 1 }}
        with:
          context: ./OCR/
          file: ./OCR/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-ocr-api:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: build-and-push-image
    environment: dev3
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: reportvision-ocr-dev3
          images: '${{ env.REGISTRY }}/${{ env.REPO}}-ocr-api:${{ env.VERSION }}'
      
