name: OCR Poetry Unit Tests
on:
  pull_request:
    paths:
      - .github/workflows/ocr-tests.yml
      - OCR/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: OCR
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt install tesseract-ocr-eng tesseract-ocr -y
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --with torch
      - name: Run tests
        run: poetry run pytest tests/ocr_test.py tests/segmentation_template_test.py tests/alignment_test.py
